# Copyright 2019 NVIDIA Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: triton-bert
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: triton-bert-client
  template:
    metadata:
      labels:
        app: triton-bert-client

    spec:
      containers:
      - name: triton-bert-client
        image: nvcr.io/nvidia/tritonserver:20.09-py3-clientsdk
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "1"
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "/workspace/install/bin/perf_client -m Bert-2 -x -1 -p 2000 -t 1 -s 0.001 -r 10000 -v -i HTTP -u 35.204.91.159:8000 -b 16 -l 500 -z --shape=input_ids:384 --shape=segment_ids:384 --shape=input_mask:384 --max-threads=1 --percentile=50" ]

        securityContext:
          runAsUser: 1000
